# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352c2f24e4f66464dfd6d9871c88a220096286e4267d480dff100a008c550c847501cba9a5834ac61d6a3f5d1130add4b3e7d5a4c90166965d1b4f80e5c33aee

test:
  secret_key_base: 695b58e42abdeed92eb432dacddf2a06f612efe2e57cb9df8369e803b7cb9c949b9729750b2807fb1b8ea0238d1563b6bca5ef3eb66d6d0c18da630bb9422d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
